/*
USE myBookshelf;
GO
--ALTER TABLE publishers WITH CHECK
--ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES zipcode(Zipcode)
--ON UPDATE CASCADE
--GO
ALTER TABLE distributors WITH CHECK
ADD CONSTRAINT FK_Zipcode2 FOREIGN KEY(Zipcode) REFERENCES zipcode(Zipcode)
ON UPDATE NO ACTION
GO
ALTER TABLE authors WITH CHECK
ADD CONSTRAINT FK_Zipcode3 FOREIGN KEY(Zipcode) REFERENCES zipcode(Zipcode)
ON UPDATE NO ACTION
GO
--ALTER TABLE books WITH CHECK
--ADD CONSTRAINT FK_PublisherID FOREIGN KEY(PublisherID) REFERENCES publishers(PublisherID)
--ON UPDATE CASCADE
--GO
--ALTER TABLE books WITH CHECK
--ADD CONSTRAINT FK_SeriesID FOREIGN KEY(SeriesID) REFERENCES series(SeriesID)
--ON UPDATE CASCADE
--GO
--ALTER TABLE bookauthor WITH CHECK
--ADD CONSTRAINT FK_Isbn FOREIGN KEY(Isbn) REFERENCES books(Isbn)
--ON UPDATE CASCADE
--GO
--ALTER TABLE bookauthor WITH CHECK
--ADD CONSTRAINT FK_AuthorID FOREIGN KEY(AuthorID) REFERENCES authors(AuthorID)
--ON UPDATE CASCADE
--GO */